##───────────────────────────────────────────────────##
######### ADS V2 SAMPLE CONFIGURATION BELOW #########
##───────────────────────────────────────────────────##

license: ${LICENSE:axiomatics_ADS.license}

domain:
  path: ${DOMAIN_CONFIG:domain.yaml}     # Local or HTTPS path to domain config

spring:
  security:
    user:
      name: ${ADS_USERNAME:admin}                # Use env var USERNAME
      password: ${PASSWORD:changeme}

authentication:
  enabled: false

##───────────────────────────────────────────────────##
######### ADS V1 SAMPLE CONFIGURATION BELOW #########
##───────────────────────────────────────────────────##

# license: ${LICENSE:-axiomatics_PDP.license}
# domain: ${DOMAIN_CONFIG:-domain.yaml}

# audit:
#   mode: verbose

# authentication:
#   type: Basic
#   user:
#     username: pdp-user
#     #password is 'secret'
#     hashPassword: 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b
# server:
#   applicationConnectors:
#     - type: http
#       port: 8081
#   adminConnectors:
#     - type: http
#       port: 8082
#   requestLog:
#     appenders:
#       - type: console
# logging:
#   level: ${LOGLEVEL:-INFO}
#   loggers:
#     "com.axiomatics": INFO
#   appenders:
#     - type: console
#       target: stdout